name: my_marvel_list
description: "MyMarvelList"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  bubble: ^1.2.1
  bulleted_list: ^0.0.1+0.1a
  collection: ^1.18.0
  crypto: ^3.0.5
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  flutter_mobx: ^2.2.1+1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  lottie: ^3.1.2
  mobx: ^2.3.3+2
  shared_preferences: ^2.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  mobx_codegen: ^2.6.1
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/animations/
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Hall of Heroes
      fonts:
        - asset: assets/fonts/Hall-of-Heroes.ttf
